version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "internet-banking-api-gateway"
          ContainerPort: 8082
        PlatformVersion: "LATEST"
