version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "internet-banking-service-registry"
          ContainerPort: 8081
        PlatformVersion: "LATEST"
